import type { RegionMeta } from '../fields/loader';

/**
 * qEEG band power projected onto cortical regions.
 *
 * The heavy lifting — BEM, forward solution, dSPM inverse — happens once in
 * `tools/prep/eeg_forward.py` and arrives as a parcels x channels matrix. All
 * that is left here is a matrix multiply over 29 numbers, which is cheap enough
 * to run on every frame of a playback.
 *
 * WHAT THIS IS NOT. Band power discards phase, so the cross-channel covariance
 * a real source reconstruction needs does not exist at runtime. This is an
 * anatomically weighted projection of the scalp topography, and the measured
 * localisation error is ~33 mm, so it resolves lobes rather than gyri.
 */

export interface EegProjection {
  subject: string;
  atlas: string;
  channels: string[];
  parcels: string[];
  matrix: number[][];
  method: string;
  limitation: string;
  gates: Record<string, { pass: boolean; note: string }>;
}

export interface QeegBands {
  channels: string[];
  bands: Record<string, [number, number]>;
  measure: string;
  limitation: string;
  measuredNegativeResult: string;
  subjects: Record<string, Record<string, number[]>>;
}

/** Floor of the encoded range; 0 is reserved to mean "no projection here". */
const MIN_VALUE = 0.02;

export const EEG_BANDS = ['delta', 'theta', 'alpha', 'beta', 'gamma', 'dar'] as const;
export type EegBand = (typeof EEG_BANDS)[number];

export class EegProjector {
  /** Region index for each row of the projection matrix, -1 if unmatched. */
  private readonly rowRegion: Int32Array;
  /** Column permutation taking qEEG channel order to projection order. */
  private readonly colOf: Int32Array;

  constructor(
    readonly proj: EegProjection,
    readonly qeeg: QeegBands,
    regions: RegionMeta[]
  ) {
    const byName = new Map(regions.map((r) => [r.name, r.index]));
    this.rowRegion = new Int32Array(proj.parcels.length);
    for (let i = 0; i < proj.parcels.length; i++) {
      this.rowRegion[i] = byName.get(proj.parcels[i]) ?? -1;
    }

    // The two files are generated by different scripts, so never assume their
    // channel orders agree — join by name and fail loudly if one is missing.
    this.colOf = new Int32Array(proj.channels.length);
    for (let j = 0; j < proj.channels.length; j++) {
      const k = qeeg.channels.indexOf(proj.channels[j]);
      if (k < 0) throw new Error(`qEEG data has no channel ${proj.channels[j]}`);
      this.colOf[j] = k;
    }
  }

  get subjects(): string[] {
    return Object.keys(this.qeeg.subjects);
  }

  /** How many projection rows failed to match a region — should be 0. */
  get unmatchedParcels(): number {
    return this.rowRegion.reduce((n, r) => n + (r < 0 ? 1 : 0), 0);
  }

  /**
   * Per-region values in 0..1, indexed by region index. Regions with no
   * projection row (subcortex, white matter, cerebellum) stay at 0 — the
   * cortical ribbon is the only thing an EEG inverse says anything about, and
   * painting deep structures would imply a claim the method cannot make.
   */
  project(subjectId: string, band: EegBand): Float32Array {
    const out = new Float32Array(256);
    const power = this.qeeg.subjects[subjectId]?.[band];
    if (!power) return out;

    const M = this.proj.matrix;
    let lo = Number.POSITIVE_INFINITY;
    let hi = Number.NEGATIVE_INFINITY;
    const raw = new Float64Array(M.length);
    for (let p = 0; p < M.length; p++) {
      const row = M[p];
      let acc = 0;
      for (let j = 0; j < row.length; j++) acc += row[j] * power[this.colOf[j]];
      raw[p] = acc;
      if (acc < lo) lo = acc;
      if (acc > hi) hi = acc;
    }

    // Normalise across parcels rather than to an absolute scale. Relative band
    // power has no meaningful zero and its range differs per band and per
    // patient, so a fixed scale would render most maps flat.
    //
    // Mapped into [MIN_VALUE, 1] rather than [0, 1] because the shader reads 0
    // as "this region has no projection" and skips it. With a plain 0..1 scale
    // the single lowest parcel normalises to exactly 0 and renders as bare
    // tissue — a hole in the map at the one place the value is most extreme.
    const span = hi - lo || 1;
    for (let p = 0; p < M.length; p++) {
      const r = this.rowRegion[p];
      if (r >= 0 && r < out.length) {
        out[r] = MIN_VALUE + (1 - MIN_VALUE) * ((raw[p] - lo) / span);
      }
    }
    return out;
  }
}

export async function loadEeg(
  base: string,
  regions: RegionMeta[]
): Promise<EegProjector | null> {
  try {
    const [proj, qeeg] = await Promise.all([
      fetch(`${base}fields/eeg_proj.json`).then((r) => r.json() as Promise<EegProjection>),
      fetch(`${base}fields/qeeg.json`).then((r) => r.json() as Promise<QeegBands>),
    ]);
    return new EegProjector(proj, qeeg, regions);
  } catch {
    // The EEG layer is optional: the renderer must work without it rather than
    // refuse to start because one prep script has not been run.
    return null;
  }
}
